substitutions:
  devicename: shelly25_bathroom_suite

packages:
  esphome_base: !include ../packages/common.yml
  esphome_web: !include ../packages/webserver.yml

  device_base: !include
    file: ../packages/shelly25.yml
    vars:
      name: Shelly 25 Master Bedroom Bathroom

  lights_base: !include
    file: ../packages/shelly25_lights.yml
    vars:
      Light_1_Name: Master Bedroom Bathroom LED
      Light_2_Name: Master Bedroom Bathroom Ceiling

  bathroom_controls: !include
    file: ../packages/bathroom_controls.yml
    vars:
      devicename: ${devicename}
      input_a_light: light_1
      input_b_light: light_2
      fan: fan.bathroom_master_bedroom
