substitutions:
  devicename: shelly1_living_room_table

esphome:
  friendly_name: Shelly 1 Living Room Table Light

packages:
  esphome_base: !include ../packages/common.yml
  esphome_web: !include ../packages/webserver.yml

  device_base: !include
    file: ../packages/shelly1.yml

binary_sensor:
  - id: sw_1
    platform: gpio
    pin:
      number: GPIO5
    on_state:
      then:
        - light.toggle: light_1

light:
  - id: light_1
    name: Living Room Table
    platform: binary
    output: relay_1
    restore_mode: RESTORE_AND_OFF
