substitutions:
  devicename: sonoff-basic-gate-lights

packages:
  esphome_base: !include ../packages/common.yml
  esphome_web: !include ../packages/webserver.yml

esphome:
  friendly_name: Sonoff Basic Gate Lights

esp8266:
  board: esp01_1m

light:
  - platform: binary
    id: light_1
    name: "Gate Lights"
    output: relay_1
    restore_mode: RESTORE_AND_OFF

output:
  - platform: gpio
    id: relay_1
    pin: GPIO12
