light:
  - id: light_1
    name: ${Light_1_Name}
    platform: binary
    output: relay_1
    restore_mode: RESTORE_DEFAULT_OFF

  - id: light_2
    name: ${Light_2_Name}
    platform: binary
    output: relay_2
    restore_mode: RESTORE_DEFAULT_OFF

sensor:
  - platform: total_daily_energy
    name: Light Daily Energy ${Light_1_Name}
    power_id: power_relay_1
    unit_of_measurement: Wh
    state_class: total_increasing
    device_class: energy
    icon: "mdi:meter-electric"

  - platform: total_daily_energy
    name: Light Daily Energy ${Light_2_Name}
    power_id: power_relay_2
    unit_of_measurement: Wh
    restore: false
    state_class: total_increasing
    device_class: energy
    icon: "mdi:meter-electric"
