# For PCB v0.1.9 with dual core ESP32
esphome:
  name_add_mac_suffix: false

esp32:
  variant: esp32c3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: recommended
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y

bluetooth_proxy:

i2c:
  sda: GPIO6
  scl: GPIO7

output:
  - platform: gpio
    id: relay_1
    pin:
      number: 5

  - platform: gpio
    id: relay_2
    pin:
      number: 3

button:
  - platform: restart
    id: restart_device

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO18
    id: sw_1
    filters:
      - delayed_on_off: 50ms

  - platform: gpio
    pin:
      number: GPIO10
    id: sw_2
    filters:
      - delayed_on_off: 50ms

  - platform: gpio
    id: reset_button
    pin:
      number: 19
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - button.press: restart_device
    filters:
      - delayed_on_off: 5ms
    internal: true

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: Device Temperature ${name}
    unit_of_measurement: "Â°C"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: 85
        then:
          - output.turn_off: relay_1
          - output.turn_off: relay_2
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${name}
              data_template:
                message: Switch turned off because max temperature was exceeded

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm

  - platform: adc
    id: temp_analog_reading
    pin: 4

status_led:
  pin:
    number: 2
    inverted: true
    ignore_strapping_warning: true
