substitutions:
  devicename: bhonofre_cover_bathroom
  CoverName: bathroom
  Open: "12"
  Close: "13"
  ExtraTop: "14"
  ExtraBottom: "2"
  CoverTime: "12s"
  SmallOpenPosition: 18%
  RelayPower: GPIO4
  RelayDirection: GPIO5
  InvertRelayDirection: "false"
  SunOrientation: "1"
  Floor: "0"

packages:
  esphome_base: !include ../packages/common.yml
  esphome_web: !include ../packages/webserver.yml
  cover: !include packages/bhonofre_cover.yml
