substitutions:
  devicename: bhonofre_cover_bedroom_ricardo
  CoverName: bedroom_ricardo
  Open: "13"
  Close: "12"
  ExtraTop: "2"
  ExtraBottom: "14"
  CoverTime: "12s"
  SmallOpenPosition: 15
  RelayPower: GPIO4
  RelayDirection: GPIO5
  InvertRelayDirection: "true"
  SunOrientation: "1"
  Floor: "1"

packages:
  esphome_base: !include ../packages/common.yml
  esphome_web: !include ../packages/webserver.yml
  cover: !include packages/bhonofre_cover.yml
