substitutions:
  devicename: bhonofre_cover_office
  CoverName: office
  Open: "14"
  Close: "12"
  ExtraTop: "2"
  ExtraBottom: "13"
  CoverTime: "14s"
  SmallOpenPosition: 15%
  RelayPower: GPIO5
  RelayDirection: GPIO4
  InvertRelayDirection: "false"
  SunOrientation: "0"
  Floor: "0"

packages:
  esphome_base: !include ../packages/common.yml
  esphome_web: !include ../packages/webserver.yml
  cover: !include packages/bhonofre_cover.yml
